name: neovision_flutter
description: Flutter app for diplom LITVIN
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get:
  dio: ^5.3.2
  jiffy: ^6.2.1
  sqflite: ^2.3.0
  timeago: ^3.5.0
  shimmer: ^3.0.0
  flutter_svg: any
  geolocator: ^9.0.2
  http_parser: ^4.0.2
  get_storage: ^2.1.1
  image_picker: ^0.8.7
  arkit_plugin: ^1.0.7
  flutter_slidable: any
  flutter_compass: ^0.7.0
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^4.0.2
  permission_handler: ^10.4.5
  image_gallery_saver: ^2.0.3
  google_maps_flutter: ^2.5.3
  flutter_image_compress: ^2.0.4
  flutter_secure_storage: ^9.0.0
  flutter_native_screenshot: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/models/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf